name: {{ cookiecutter.repo_name }}
channels:
  - conda-forge
  - defaults
dependencies:
  - azure-storage-blob
  - black
  - flake8
  - ipykernel
  - joblib
  - jupyter
  - jupyter_contrib_nbextensions
  - jupytext
  - make
  - matplotlib
  - myst-parser
  - nbconvert
  - numpy
  - pandas
  - pandoc
  - pip
  - pre-commit
  - pylint
  - python=3.8
  - python-dotenv
  - seaborn
  - scikit-learn
  - scipy
  - pip:
      - azure-kusto-data
